#!/usr/bin/env python3
"""Patch known gaps in autogenerated third-party stubs."""

from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UTIL_PYI = ROOT / "typings" / "apscheduler" / "util.pyi"
BASE_PYI = ROOT / "typings" / "apscheduler" / "schedulers" / "base.pyi"
BLOCKING_PYI = ROOT / "typings" / "apscheduler" / "schedulers" / "blocking.pyi"

MISSING_UTIL_EXPORTS = """
def datetime_utc_add(dateval, tdelta): ...
def datetime_repr(dateval): ...
"""

BASE_IMPORTS = "from collections.abc import Callable\nfrom typing import Any\n"

OLD_ADD_JOB = (
    "    def add_job(self, func, trigger=None, args=None, kwargs=None, id=None, name=None, "
    "misfire_grace_time=..., coalesce=..., max_instances=..., next_run_time=..., "
    "jobstore: str = 'default', executor: str = 'default', replace_existing: bool = False, "
    "**trigger_args): ..."
)

NEW_ADD_JOB = """    def add_job(
        self,
        func: Callable[..., object],
        trigger: BaseTrigger | None = None,
        args: list[Any] | tuple[Any, ...] | None = None,
        kwargs: dict[str, Any] | None = None,
        id: str | None = None,
        name: str | None = None,
        misfire_grace_time: Any = ...,
        coalesce: Any = ...,
        max_instances: Any = ...,
        next_run_time: Any = ...,
        jobstore: str = 'default',
        executor: str = 'default',
        replace_existing: bool = False,
        **trigger_args: Any,
    ) -> Job: ..."""


def patch_apscheduler_util() -> None:
    if not UTIL_PYI.exists():
        return

    text = UTIL_PYI.read_text()
    if "datetime_repr" in text:
        return

    UTIL_PYI.write_text(text.rstrip() + "\n" + MISSING_UTIL_EXPORTS)


def patch_apscheduler_base() -> None:
    if not BASE_PYI.exists():
        return

    text = BASE_PYI.read_text()
    if "Callable[..., object]" in text:
        return

    if "from collections.abc import Callable" not in text:
        text = BASE_IMPORTS + text

    if OLD_ADD_JOB not in text:
        raise RuntimeError("Expected add_job signature not found in base.pyi; stubgen output may have changed")

    BASE_PYI.write_text(text.replace(OLD_ADD_JOB, NEW_ADD_JOB))


def patch_apscheduler_blocking() -> None:
    if not BLOCKING_PYI.exists():
        return

    text = BLOCKING_PYI.read_text()
    updated = text.replace(
        "def start(self, *args, **kwargs) -> None: ...",
        "def start(self, *args: object, **kwargs: object) -> None: ...",
    )
    if updated != text:
        BLOCKING_PYI.write_text(updated)


def main() -> None:
    patch_apscheduler_util()
    patch_apscheduler_base()
    patch_apscheduler_blocking()
    print("Stub patches applied.")


if __name__ == "__main__":
    main()
